name: CI Setup
description: "Sets up the environment for jobs during CI workflow"

inputs:
  flux-username:
    description: "Flux UI Pro username"
    required: true
  flux-license-key:
    description: "Flux UI Pro license key"
    required: true

runs:
  using: composite
  steps:
    - name: ðŸ˜ Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_pgsql, bcmath, soap, intl, gd, exif, iconv, imagick
        tools: composer:latest
        coverage: xdebug
    - name: â„¹ Setup Problem Matches
      shell: sh
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
    - name: Add Flux Credentials Loaded From ENV
      shell: sh
      run: composer config http-basic.composer.fluxui.dev "${{ inputs.flux-username }}" "${{ inputs.flux-license-key }}"
    - name: ðŸ—‚ Get composer cache directory
      id: composer-cache
      shell: sh
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - name: Cache dependencies
      uses: actions/cache@v5
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
