name: Update Changelog

on:
  release:
    types:
      - released

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: changelog-${{ github.event.release.name }}
          commit_message: "chore: update CHANGELOG for ${{ github.event.release.name }}"
          file_pattern: CHANGELOG.md
          create_branch: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: changelog-${{ github.event.release.name }}
          base: main
          commit-message: "chore: update CHANGELOG for ${{ github.event.release.name }}"
          title: "chore: update CHANGELOG for ${{ github.event.release.name }}"
          body: |
            This PR updates the CHANGELOG for release ${{ github.event.release.name }}.

            **Auto-generated by GitHub Actions**
